In [1]:
# ============================================
# NLP LAB - 1
# Text Preprocessing and N-gram Analysis
# Priyanshu Thakur (S24CSEU2222)
# ============================================

import nltk
import pandas as pd
import string
from collections import Counter
from difflib import get_close_matches

resources = [
    'brown',
    'stopwords',
    'punkt',
    'punkt_tab',
    'words',
    'wordnet',
    'omw-1.4'
]

for resource in resources:
    nltk.download(resource, quiet=True)

print("All NLTK resources downloaded successfully!")

All NLTK resources downloaded successfully!

In [2]:
from nltk.corpus import brown, stopwords
from nltk.tokenize import sent_tokenize, word_tokenize


brown_sentences = brown.sents()


selected_sentences = [' '.join(sentence) for sentence in brown_sentences[:20]]

print("Number of selected sentences:", len(selected_sentences))
print("\nFirst 5 Original Sentences:\n")

for i, sentence in enumerate(selected_sentences[:5], 1):
    print(f"{i}. {sentence}")

Number of selected sentences: 20

First 5 Original Sentences:

1. The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .
2. The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .
3. The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .
4. `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .
5. The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .

In [3]:

text = " ".join(selected_sentences)

sentence_tokens = sent_tokenize(text)


word_tokens = word_tokenize(text)

print("Total Sentence Tokens:", len(sentence_tokens))
print("Total Word Tokens:", len(word_tokens))

print("\nSentence Tokens:")
print(sentence_tokens[:5])

print("\nWord Tokens:")
print(word_tokens[:30])

Total Sentence Tokens: 19
Total Word Tokens: 529

Sentence Tokens:
["The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .", "The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .", "The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .", "`` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .", "The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' ."]

Word Tokens:
['The', 'Fulton', 'County', 'Grand', 'Jury', 'said', 'Friday', 'an', 'investigation', 'of', 'Atlanta', "'s", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', '``', 'that', 'any', 'irregularities', 'took', 'place', '.', 'The', 'jury', 'further', 'said']

In [4]:

stop_words = set(stopwords.words('english'))


lower_tokens = [word.lower() for word in word_tokens]


cleaned_tokens = [
    word for word in lower_tokens
    if word.isalpha() and word not in stop_words
]

print("Original number of tokens:", len(word_tokens))
print("Cleaned number of tokens:", len(cleaned_tokens))

print("\nCleaned Tokens:")
print(cleaned_tokens[:50])

Original number of tokens: 529
Cleaned number of tokens: 252

Cleaned Tokens:
['fulton', 'county', 'grand', 'jury', 'said', 'friday', 'investigation', 'atlanta', 'recent', 'primary', 'election', 'produced', 'evidence', 'irregularities', 'took', 'place', 'jury', 'said', 'presentments', 'city', 'executive', 'committee', 'charge', 'election', 'deserves', 'praise', 'thanks', 'city', 'atlanta', 'manner', 'election', 'conducted', 'term', 'jury', 'charged', 'fulton', 'superior', 'court', 'judge', 'durwood', 'pye', 'investigate', 'reports', 'possible', 'irregularities', 'primary', 'ivan', 'allen', 'relative', 'handful']

In [5]:
print("=" * 80)
print("ORIGINAL AND CLEANED SENTENCES")
print("=" * 80)

for i in range(5):
    original = selected_sentences[i]


    tokens = word_tokenize(original.lower())

    cleaned = [
        word for word in tokens
        if word.isalpha() and word not in stop_words
    ]

    print(f"\nSentence {i+1}")
    print("Original :", original)
    print("Tokens   :", tokens)
    print("Cleaned  :", cleaned)

================================================================================
ORIGINAL AND CLEANED SENTENCES
================================================================================

Sentence 1
Original : The Fulton County Grand Jury said Friday an investigation of Atlanta's recent primary election produced `` no evidence '' that any irregularities took place .
Tokens   : ['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'atlanta', "'s", 'recent', 'primary', 'election', 'produced', '``', 'no', 'evidence', '``', 'that', 'any', 'irregularities', 'took', 'place', '.']
Cleaned  : ['fulton', 'county', 'grand', 'jury', 'said', 'friday', 'investigation', 'atlanta', 'recent', 'primary', 'election', 'produced', 'evidence', 'irregularities', 'took', 'place']

Sentence 2
Original : The jury further said in term-end presentments that the City Executive Committee , which had over-all charge of the election , `` deserves the praise and thanks of the City of Atlanta '' for the manner in which the election was conducted .
Tokens   : ['the', 'jury', 'further', 'said', 'in', 'term-end', 'presentments', 'that', 'the', 'city', 'executive', 'committee', ',', 'which', 'had', 'over-all', 'charge', 'of', 'the', 'election', ',', '``', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'city', 'of', 'atlanta', '``', 'for', 'the', 'manner', 'in', 'which', 'the', 'election', 'was', 'conducted', '.']
Cleaned  : ['jury', 'said', 'presentments', 'city', 'executive', 'committee', 'charge', 'election', 'deserves', 'praise', 'thanks', 'city', 'atlanta', 'manner', 'election', 'conducted']

Sentence 3
Original : The September-October term jury had been charged by Fulton Superior Court Judge Durwood Pye to investigate reports of possible `` irregularities '' in the hard-fought primary which was won by Mayor-nominate Ivan Allen Jr. .
Tokens   : ['the', 'september-october', 'term', 'jury', 'had', 'been', 'charged', 'by', 'fulton', 'superior', 'court', 'judge', 'durwood', 'pye', 'to', 'investigate', 'reports', 'of', 'possible', '``', 'irregularities', '``', 'in', 'the', 'hard-fought', 'primary', 'which', 'was', 'won', 'by', 'mayor-nominate', 'ivan', 'allen', 'jr.', '.']
Cleaned  : ['term', 'jury', 'charged', 'fulton', 'superior', 'court', 'judge', 'durwood', 'pye', 'investigate', 'reports', 'possible', 'irregularities', 'primary', 'ivan', 'allen']

Sentence 4
Original : `` Only a relative handful of such reports was received '' , the jury said , `` considering the widespread interest in the election , the number of voters and the size of this city '' .
Tokens   : ['``', 'only', 'a', 'relative', 'handful', 'of', 'such', 'reports', 'was', 'received', '``', ',', 'the', 'jury', 'said', ',', '``', 'considering', 'the', 'widespread', 'interest', 'in', 'the', 'election', ',', 'the', 'number', 'of', 'voters', 'and', 'the', 'size', 'of', 'this', 'city', '``', '.']
Cleaned  : ['relative', 'handful', 'reports', 'received', 'jury', 'said', 'considering', 'widespread', 'interest', 'election', 'number', 'voters', 'size', 'city']

Sentence 5
Original : The jury said it did find that many of Georgia's registration and election laws `` are outmoded or inadequate and often ambiguous '' .
Tokens   : ['the', 'jury', 'said', 'it', 'did', 'find', 'that', 'many', 'of', 'georgia', "'s", 'registration', 'and', 'election', 'laws', '``', 'are', 'outmoded', 'or', 'inadequate', 'and', 'often', 'ambiguous', '``', '.']
Cleaned  : ['jury', 'said', 'find', 'many', 'georgia', 'registration', 'election', 'laws', 'outmoded', 'inadequate', 'often', 'ambiguous']

In [6]:
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.corpus import brown


all_words = [
    word.lower()
    for word in brown.words()
    if word.isalpha()
]


selected_words = all_words[:30]


required_words = [
    "playing",
    "studies",
    "running",
    "better",
    "cars"
]

selected_words = selected_words + required_words


stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()


pos_map = {
    "playing": "v",
    "studies": "n",
    "running": "v",
    "better": "a",
    "cars": "n"
}


data = []

for word in selected_words:
    stem = stemmer.stem(word)

    if word in pos_map:
        lemma = lemmatizer.lemmatize(word, pos=pos_map[word])
    else:
        lemma = lemmatizer.lemmatize(word)

    data.append([word, stem, lemma])

df = pd.DataFrame(
    data,
    columns=["Original Word", "Stemmed Word", "Lemmatized Word"]
)

print("Stemming vs Lemmatization:")
display(df)

Stemming vs Lemmatization:

     Original Word Stemmed Word Lemmatized Word
0              the          the             the
1           fulton       fulton          fulton
2           county       counti          county
3            grand        grand           grand
4             jury         juri            jury
5             said         said            said
6           friday       friday          friday
7               an           an              an
8    investigation     investig   investigation
9               of           of              of
10          recent       recent          recent
11         primary      primari         primary
12        election        elect        election
13        produced       produc        produced
14              no           no              no
15        evidence         evid        evidence
16            that         that            that
17             any          ani             any
18  irregularities    irregular    irregularity
19            took         took            took
20           place        place           place
21             the          the             the
22            jury         juri            jury
23         further      further         further
24            said         said            said
25              in           in              in
26    presentments      present     presentment
27            that         that            that
28             the          the             the
29            city         citi            city
30         playing         play            play
31         studies        studi           study
32         running          run             run
33          better       better            good
34            cars          car             car

In [7]:
print("Required Examples:")
display(
    df[df["Original Word"].isin(
        ["playing", "studies", "running", "better", "cars"]
    )]
)

Required Examples:

   Original Word Stemmed Word Lemmatized Word
30       playing         play            play
31       studies        studi           study
32       running          run             run
33        better       better            good
34          cars          car             car

In [8]:
from nltk.corpus import words

word_vocabulary = set(
    word.lower()
    for word in words.words()
    if word.isalpha()
)

print("Total vocabulary words:", len(word_vocabulary))

misspelled_words = [
    "recieve",
    "teh",
    "definately",
    "seperate",
    "enviroment",
    "becuase",
    "langauge",
    "computar",
    "studing",
    "progrmming"
]

print("\nMisspelled Words:")
print(misspelled_words)

Total vocabulary words: 234375

Misspelled Words:
['recieve', 'teh', 'definately', 'seperate', 'enviroment', 'becuase', 'langauge', 'computar', 'studing', 'progrmming']

In [9]:
def correct_spelling(word, vocabulary, n=3):
    """
    Find the closest words from the NLTK vocabulary.
    """
    suggestions = get_close_matches(
        word.lower(),
        vocabulary,
        n=n,
        cutoff=0.60
    )

    return suggestions



spelling_results = []

for word in misspelled_words:
    suggestions = correct_spelling(word, word_vocabulary)

    spelling_results.append([
        word,
        ", ".join(suggestions) if suggestions else "No suggestion"
    ])

spelling_df = pd.DataFrame(
    spelling_results,
    columns=["Misspelled Word", "Suggested Corrections"]
)

display(spelling_df)

  Misspelled Word                  Suggested Corrections
0         recieve            reachieve, relieve, receive
1             teh                         teth, tech, th
2      definately       definitely, dentately, definedly
3        seperate            sperate, separate, asperate
4      enviroment  environment, environmental, enrolment
5         becuase              bedcase, becurse, bechase
6        langauge          language, langrage, slanguage
7        computar             computer, copular, compute
8         studing             studding, strouding, suing
9      progrmming         progambling, poring, stromming

In [10]:

example_sentences = [
    "I recieve many messages every day.",
    "Teh student is studying NLP.",
    "This is definately a useful subject.",
    "We need to seperate the words.",
    "The enviroment affects our learning.",
    "I missed the class becuase I was sick."
]

correction_map = {
    "recieve": "receive",
    "teh": "the",
    "definately": "definitely",
    "seperate": "separate",
    "enviroment": "environment",
    "becuase": "because"
}

corrected_sentences = []

for sentence in example_sentences:
    corrected = sentence

    for wrong, correct in correction_map.items():
        corrected = corrected.replace(wrong, correct)
        corrected = corrected.replace(
            wrong.capitalize(),
            correct.capitalize()
        )

    corrected_sentences.append(corrected)

print("=" * 80)
print("SPELLING CORRECTION - SENTENCE EXAMPLES")
print("=" * 80)

for i in range(len(example_sentences)):
    print(f"\nExample {i+1}")
    print("Original :", example_sentences[i])
    print("Corrected:", corrected_sentences[i])

================================================================================
SPELLING CORRECTION - SENTENCE EXAMPLES
================================================================================

Example 1
Original : I recieve many messages every day.
Corrected: I receive many messages every day.

Example 2
Original : Teh student is studying NLP.
Corrected: The student is studying NLP.

Example 3
Original : This is definately a useful subject.
Corrected: This is definitely a useful subject.

Example 4
Original : We need to seperate the words.
Corrected: We need to separate the words.

Example 5
Original : The enviroment affects our learning.
Corrected: The environment affects our learning.

Example 6
Original : I missed the class becuase I was sick.
Corrected: I missed the class because I was sick.

In [11]:
from nltk.util import ngrams


brown_words = brown.words()

clean_brown_tokens = [
    word.lower()
    for word in brown_words
    if word.isalpha()
]

print("Total cleaned Brown Corpus tokens:", len(clean_brown_tokens))

print("\nFirst 50 tokens:")
print(clean_brown_tokens[:50])

Total cleaned Brown Corpus tokens: 981716

First 50 tokens:
['the', 'fulton', 'county', 'grand', 'jury', 'said', 'friday', 'an', 'investigation', 'of', 'recent', 'primary', 'election', 'produced', 'no', 'evidence', 'that', 'any', 'irregularities', 'took', 'place', 'the', 'jury', 'further', 'said', 'in', 'presentments', 'that', 'the', 'city', 'executive', 'committee', 'which', 'had', 'charge', 'of', 'the', 'election', 'deserves', 'the', 'praise', 'and', 'thanks', 'of', 'the', 'city', 'of', 'atlanta', 'for', 'the']

In [12]:

unigrams = list(ngrams(clean_brown_tokens, 1))


bigrams = list(ngrams(clean_brown_tokens, 2))


trigrams = list(ngrams(clean_brown_tokens, 3))

print("Total Unigrams :", len(unigrams))
print("Total Bigrams  :", len(bigrams))
print("Total Trigrams :", len(trigrams))

print("\nSample Unigrams:")
print(unigrams[:10])

print("\nSample Bigrams:")
print(bigrams[:10])

print("\nSample Trigrams:")
print(trigrams[:10])

Total Unigrams : 981716
Total Bigrams  : 981715
Total Trigrams : 981714

Sample Unigrams:
[('the',), ('fulton',), ('county',), ('grand',), ('jury',), ('said',), ('friday',), ('an',), ('investigation',), ('of',)]

Sample Bigrams:
[('the', 'fulton'), ('fulton', 'county'), ('county', 'grand'), ('grand', 'jury'), ('jury', 'said'), ('said', 'friday'), ('friday', 'an'), ('an', 'investigation'), ('investigation', 'of'), ('of', 'recent')]

Sample Trigrams:
[('the', 'fulton', 'county'), ('fulton', 'county', 'grand'), ('county', 'grand', 'jury'), ('grand', 'jury', 'said'), ('jury', 'said', 'friday'), ('said', 'friday', 'an'), ('friday', 'an', 'investigation'), ('an', 'investigation', 'of'), ('investigation', 'of', 'recent'), ('of', 'recent', 'primary')]

In [13]:

unigram_freq = Counter(unigrams)
bigram_freq = Counter(bigrams)
trigram_freq = Counter(trigrams)


top_unigrams = unigram_freq.most_common(10)
top_bigrams = bigram_freq.most_common(10)
top_trigrams = trigram_freq.most_common(10)

print("TOP 10 UNIGRAMS")
print("-" * 40)

for item, frequency in top_unigrams:
    print(item[0], ":", frequency)

print("\nTOP 10 BIGRAMS")
print("-" * 40)

for item, frequency in top_bigrams:
    print(" ".join(item), ":", frequency)

print("\nTOP 10 TRIGRAMS")
print("-" * 40)

for item, frequency in top_trigrams:
    print(" ".join(item), ":", frequency)

TOP 10 UNIGRAMS
----------------------------------------
the : 69971
of : 36412
and : 28853
to : 26158
a : 23195
in : 21337
that : 10594
is : 10109
was : 9815
he : 9548

TOP 10 BIGRAMS
----------------------------------------
of the : 9774
in the : 6156
to the : 3525
on the : 2491
and the : 2307
for the : 1862
to be : 1718
at the : 1677
with the : 1545
of a : 1502

TOP 10 TRIGRAMS
----------------------------------------
one of the : 404
the united states : 337
as well as : 238
some of the : 179
out of the : 174
the fact that : 167
the end of : 149
part of the : 146
it was a : 144
there was a : 142

In [14]:


unigram_df = pd.DataFrame(
    [(item[0], freq) for item, freq in top_unigrams],
    columns=["Unigram", "Frequency"]
)

bigram_df = pd.DataFrame(
    [(" ".join(item), freq) for item, freq in top_bigrams],
    columns=["Bigram", "Frequency"]
)

trigram_df = pd.DataFrame(
    [(" ".join(item), freq) for item, freq in top_trigrams],
    columns=["Trigram", "Frequency"]
)

print("Top 10 Unigrams")
display(unigram_df)

print("Top 10 Bigrams")
display(bigram_df)

print("Top 10 Trigrams")
display(trigram_df)

Top 10 Unigrams

  Unigram  Frequency
0     the      69971
1      of      36412
2     and      28853
3      to      26158
4       a      23195
5      in      21337
6    that      10594
7      is      10109
8     was       9815
9      he       9548

Top 10 Bigrams

     Bigram  Frequency
0    of the       9774
1    in the       6156
2    to the       3525
3    on the       2491
4   and the       2307
5   for the       1862
6     to be       1718
7    at the       1677
8  with the       1545
9      of a       1502

Top 10 Trigrams

             Trigram  Frequency
0         one of the        404
1  the united states        337
2         as well as        238
3        some of the        179
4         out of the        174
5      the fact that        167
6         the end of        149
7        part of the        146
8           it was a        144
9        there was a        142

In [15]:
print("""
N-GRAM ANALYSIS
===============

1. Unigram:
   A unigram contains only one word.
   Example: "natural"

2. Bigram:
   A bigram contains two consecutive words.
   Example: "natural language"

3. Trigram:
   A trigram contains three consecutive words.
   Example: "natural language processing"

As N increases, the model captures more contextual information.

Unigrams provide individual word information.
Bigrams provide relationships between two consecutive words.
Trigrams provide relationships between three consecutive words.

Therefore, trigrams generally capture more context than bigrams,
while bigrams capture more context than unigrams.
""")

N-GRAM ANALYSIS
===============

1. Unigram:
   A unigram contains only one word.
   Example: "natural"

2. Bigram:
   A bigram contains two consecutive words.
   Example: "natural language"

3. Trigram:
   A trigram contains three consecutive words.
   Example: "natural language processing"

As N increases, the model captures more contextual information.

Unigrams provide individual word information.
Bigrams provide relationships between two consecutive words.
Trigrams provide relationships between three consecutive words.

Therefore, trigrams generally capture more context than bigrams,
while bigrams capture more context than unigrams.